use_frameworks!

target 'podTestLib_Example', :exclusive => true do
  pod 'podTestLib', :path => '../'
end

target 'podTestLib_Tests', :exclusive => true do
  pod 'podTestLib', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
